# Generated by Django 5.0.6 on 2024-05-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_customer_alter_orderitems_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerAddressItems',
            new_name='CustomerAddress',
        ),
    ]
